### ISSUE TITLE
libusb Error

### ISSUE THREAD

**Issue by binary42** [dji-sdk/Guidance-SDK#10]
Greetings. Given the following description of our attempt at setting up the Guidance SDK, we have failed to get beyond:

llibusb_get_device_list ret = 10 !!!
Waiting for board ready...
Error: e_stereo_cali_not_ready at 149,main.cpp

----Procedure Used----

# DJI Guidance Troubleshooting Notes

Below is my entire process for building and running the USB example code that ships with the [DJI Guidance SDK](https://github.com/dji-sdk/Guidance-SDK). The steps I follow come from the [Developer Guide](https://github.com/dji-sdk/Guidance-SDK/blob/master/doc/Guides/Developer_Guide/en/DeveloperGuide_en.md).

The following was performed on a brand new installation of Ubuntu 14.04.

## Installing libusb

I download and extract Version 1.0.9 from the [libusb website](http://www.libusb.org). I extract the files into my `/home` directory. I then go into the new directory containing the libusb files and install libusb like so:

```sh
$ cd ~/libusb-1.0.9/
$ ./configure
$ make
$ sudo make install
```

## Installing Other Dependencies

I install `g++` and `libopencv-dev`:

```sh
$ sudo apt-get install g++
$ sudo apt-get install libopencv-dev
```

## Getting the Guidance SDK

I clone the Guidance SDK repository to my `/home` directory:

```sh
$ cd
$ git clone https://github.com/dji-sdk/Guidance-SDK.git
```

I then copy the appropriate `.so` file to both `/usr/local/lib` and the directory containing the USB example code. The `.so` files are located in `~/Guidance-SDK/so`. I'm using an x64 machine, so I use the x64 `.so`:

```sh
$ cd ~/Guidance-SDK/so/x64/
$ sudo cp libDJI_guidance.so /usr/local/lib
$ cp libDJI_guidance.so ~/Guidance-SDK/examples/usb_example/DJI_guidance_example/
```

## Building the USB Example Code

```sh
$ cd ~/Guidance-SDK/examples/usb_example/DJI_guidance_example/
$ make
```

## Setting Device Rules (Optional)

I set the following device rule per DJI's instructions. This allows me to use the DJI Guidance without `sudo`:

```sh
$ sudo sh -c 'echo "SUBSYSTEM==\"usb\", ATTR{idVendor}==\"fff0\", ATTR{idProduct}==\"d009\", MODE=\"0666\"" > /etc/udev/rules.d/51-guidance.rules'
```

## Running the USB Example Code

After building the USB example code, I power on the DJI Guidance using a power supply giving 12.2 volts. After the green lights on the Guidance come on, I plug it in via USB and try to run the following:

```sh
sudo ./guidance_example
```

Each time, I get the following output:

```
llibusb_get_device_list ret = 10 !!!
Waiting for board ready...
Error: e_stereo_cali_not_ready at 149,main.cpp
```

Any help would be greatly appreciated

Regards

**Comment by tangketan** [comment]
It is likely that your Guidance's firmware version isn't correct. The SDK is for 1.3.7. Please use Guidance Assistant software to update your Guidance to the latest version.
