### ISSUE TITLE
Obstacle Bypass demo can not run 

### ISSUE THREAD

**Issue by YjyJeff** [dji-sdk/Guidance-SDK#11]
when I run the Obstacle Bypass demo ,it displays follows:
root@tegra-ubuntu:~/Guidance-SDK/demo/obstacle_bypass/balance_strategy# ./devel/lib/dji_sdk/dji_sdk_node 
Test SDK Protocol demo
[INIT] SET serial_port	: /dev/ttyUSB0 
[INIT] SET baud_rate	: 230400 
[INIT] ACTIVATION INFO	: 
[INIT] 	  app_id     	  1010572 
[INIT]    app_api_level	  2 
[INIT]    app_version     1 
[INIT]    app_bundle_id	  12345678901234567890123456789012 
[INIT]    enc_key	  ca5aed46d675076dd100ec73a8d3b8d3dbeea66392c77af62ac65cf9b5be8520 
SerialOpen,24:ERROR
llibusb_get_device_list ret = 6 !!! 
Waiting for board ready...

Running Mission...
[ACTIVATION] send acticition msg: 1010572 2 1 49 

And it stops here ...So how can I solve the problem? I connect the Guidance with ManiFold through USB.

**Comment by pifordi** [comment]
Hi YjyJeff,
How to run the demo? Could you explain it?
