### ISSUE TITLE
usb_example/main.cpp code syntax error

### ISSUE THREAD

**Issue by mannly01** [dji-sdk/Guidance-SDK#16]
While trying to run the usb_example code on 3 different Linux systems I encountered multiple and completely random errors.  I have troubleshot my specific problems to the syntax error described below:

Line 230 shows this `if (key > 0)` and then immediately moves into another if statement on Line 231 `if(key=='j' || key=='k' || key=='m' || key=='n'){`.

If you notice, Line 230 does not have a `{` at the end of the line.  When this code is executed and no key is pressed, the `if` statement on Line 231 is ignored, but the `else` statement on Line 252 is then executed.  When running this code on a NVIDIA Jetson TK1, Line 254 `destroyAllWindows();` was continuously running through every loop and blocking the system.  The same thing was happening with the Raspberry Pi 2.

The quick fix is to put a `{` at the end of Line 230 and add a line after Line 276 with a `}`.

While I was optimizing the code, I also changed Line 252 `else {// switch image direction` to `else if(key=='q' || key=='w' || key=='d' || key=='x' || key=='a' || key=='s') {//switch image direction` so that code would only execute when the user pressed one of the 'option' keys.

The program seemed to gain quite a bit of speed and allowed all of the 'options' to be used.

**Comment by tangketan** [comment]
Thanks a lot! The code is modified according to your suggestion.
