### ISSUE TITLE
frame index and timestamps

### ISSUE THREAD

**Issue by andre-nguyen** [dji-sdk/Guidance-SDK#21]
Quick question, I don't have my Guidance unit with me to test but I would like to have an official answer on this.

I'm assuming the stereo image pairs are internally synchronized, how do you go about matching the left and right image from a camera module, will they have the same frame_index or the same timestamp? Or both?

**Comment by tangketan** [comment]
Yes, both. They are both members of struct `image_data`, thus they share same frame_index and timestamp.
