### ISSUE TITLE
imu data is always zeros

### ISSUE THREAD

**Issue by longlong2010** [dji-sdk/Guidance-SDK#22]
In DJI_guidance_example
```c++
	if ( e_imu == data_type && NULL != content )
	{
		imu *imu_data = (imu*)content;
		printf( "imu:%f %f %f,%f %f %f %f\n", imu_data->acc_x, imu_data->acc_y, imu_data->acc_z, imu_data->q[0], imu_data->q[1], imu_data->q[2], imu_data->q[3] );
		printf("imu:%d\n", imu_data->time_stamp);
		printf( "frame index:%d,stamp:%d\n", imu_data->frame_index, imu_data->time_stamp );
	}
```
The output of imu data is always seven zeros

**Comment by longlong2010** [comment]
I change Guidance working mode to DIY by Guidance Assistant, as the docs says that While in DIY mode, IMU data can always be output without connecting to a flight controller. So what's the reason? Expecting an answer. Thanks very much.

**Comment by tangketan** [comment]
Sorry for the confusion. The doc's description is true only for firmware version 1.3.7 and below. For the latest version 1.4.0, you have to connect to flight controller to get IMU data. 
If you really want this feature, you can use the Guidance Assistant v1.2 to revert firmware to version 1.3.7.

**Comment by longlong2010** [comment]
I use the Guidance Assistant v1.2 to revert firmware, but it still 1.4.0 after finished. Any help, Thanks very much.

**Comment by longlong2010** [comment]
After try several times, it works as last. Thanks very mush!

**Comment by raghavkhanna** [comment]
Hi @tangketan,

Thanks for your answer. It solves our issue for now. However, since the Guidance is advertised as having the ability be used with other robots as well (and not only the DJI M100), I'd appreciate it if you enable imu data in DIY mode in future releases.

Thanks

**Comment by Aswath93** [comment]
Hey guys,

I want to revert back to v1.2 as I need to read the guidance's IMU data. I could not find the older version of dji guidance assistant anywhere. Could someone help me resolve this?

Thanks

**Comment by AldrichCabrera** [comment]
Hi Aswath, 

I download dji assistant v1.2 for my matrice 100. In the contact part search guidance and fortunately i found the program guidance assistan 1.2v and the firmaware 1.3.7. I hope help you!!!

**Comment by menzehua** [comment]
I can't find the dji assistantv1.2 ,can anyone share one?thanks
