### ISSUE TITLE
ultrasonic_data reliability

### ISSUE THREAD

**Issue by wuqibh** [dji-sdk/Guidance-SDK#4]
There is a parameter in ultrasonic_data called reliability. It varies from 0 to 65535. I want to know is the bigger one more reliable? or  the other way around? And I get 5 direction data, sometimes 2 of the reliability are 1, 1 is of the reliability  is 0, the other 2 could be 10000+. Is there any problem?

**Comment by tangketan** [comment]
Although reliability is int, currently we use only 0 or 1 to indicate the quality of sonar: 1 means reliable, 0  means unreliable, and other numbers mean"unknown" .
