### ISSUE TITLE
usb_example/guidance_example fails at init_transfer()

### ISSUE THREAD

**Issue by ompugao** [dji-sdk/Guidance-SDK#8]
init_transfer fails with error_code 8 on ubuntu 14.04 x86_64.
I've already calibrated all stereo cameras using guidance assistant on windows.
I cannot guess what's going on inside guidance...

what should i do? what should i check?

**Comment by tangketan** [comment]
Please check if you start the SDK program too early: Guidance needs a while to prepare all data for SDK program, including stereo calibration params. So it is suggested to start your SDK program **after the LEDs on Guidance Sensor turn solid green. which means Guidance is fully started**.

**Comment by ompugao** [comment]
thanks for your quick response!

yes, I always confirm that all LEDs on sensors are green.

should i attach sensors somewhere? now, i'm trying to check if i can fetch data from guidance or not, so i just calibrate sensors one by one and launch usb_example program.
does it work correctly?

are there some extra procedures to save stereo calibration parameters to sensors?
I just launch guidance assistant and calibrate sensors following this video https://www.youtube.com/watch?v=hv4sJc9dezA .
guidance assistant saves parameters to sensors(?) automatically, right?

btw, after the LEDs become green, I can hear a low humming noise from sensors.
is it a correct behavior?

**Comment by ompugao** [comment]
any progress?

**Comment by eomargr** [comment]
I'm using Ubuntu 14.04, ROS Indigo and I'm experiencing the same error on GuidanceNode.cpp

I've calibrated all the cameras on Windows and then on Linux I've waited for green LEDs, but the error keeps showing:
llibusb_get_device_list ret = 8 !!! 
Waiting for board ready...
Error: e_stereo_cali_not_ready at 237, .../src/Guidance-SDK-ROS/src/GuidanceNode.cpp

Even after waiting for more than ten minutes, the calibration parameters are missing. 

Any clue what to do?

**Comment by eomargr** [comment]
DJI just released firmware 1.3.7, the problem was solved applying the update.

**Comment by ompugao** [comment]
good news!

**Comment by eomargr** [comment]
You can update the firmware using the DJI's official software (assistant) for Windows.

**Comment by tangketan** [comment]
Yes, 1.3.7 solved the problem. 
ompugao, sorry for the late reply..

**Comment by ompugao** [comment]
yeah! It works now! thanks a lot, guys!

**Comment by menzehua** [comment]
is there anyone have the software guidance assistant v1.2?thanks

**Comment by tangketan** [comment]
@menzehua luckily you can download it from here: https://www.dji.com/zh-tw/guidance/info#downloads
