### ISSUE TITLE
Incomplete depth imagery

### ISSUE THREAD

**Issue by mcguire-steve** [dji-sdk/Guidance-SDK#9]
When using the usb_example on x64 Linux, my depth images have a ~70px black border on the left side. This represents almost a quarter of the image and decreases the utility of the depth output. Can this be resolved? Screenshot attached. 
![guidance_black_bar_depth](https://cloud.githubusercontent.com/assets/5855021/11157845/303d3a1c-8a11-11e5-8740-0405337b316a.png)

**Comment by madratman** [comment]
Hey, can you try my fork of the Guidance-ROS-SDK, and see if that helps? I have explained in the last section of the Readme here https://github.com/madratman/Guidance-SDK-ROS and made a pull request here https://github.com/dji-sdk/Guidance-SDK-ROS/pull/5

**Comment by mcguire-steve** [comment]
I appreciate the input, but using a CPU solution isn't the answer. Somebody from DJI needs to address this problem. According to the documentation of Guidance, the FPGA pipeline should be able to do the stereo reconstruction to produce a depth map - I don't have the CPU resources to do this on a host in my application. That's the whole point of spending the money on this system vs using discrete cameras and a software pipeline.

**Comment by tangketan** [comment]
Currently several left most columns do not have depth values, due to that stereo matching doesn't have enough search range and can't give accurate estimation. Therefore we choose not to provide those inaccurate values.

**Comment by madratman** [comment]
Agreed @mcguire-steve. I have an odroid onboard though. 
@tangketan, so maybe this is another to provide raw images so that we can play around as well. But, what @mcguire-steve mentioned is important as well. 
Also, if you guys have more suggestions about the [PR](https://github.com/dji-sdk/Guidance-SDK-ROS/pull/5), I would be interested in trying my hand.

**Comment by tangketan** [comment]
Yes, currently we can only provide a non-full depth image, which is registered to the left grayscale image. However we have the potential to provide full depth images.

**Comment by andre-nguyen** [comment]
Is it just me or are the Guidance depth images incredibly noisy compared to what you get just by doing standard OpenCV block matching e.g. using ROS stereo_image_proc? I getting something similar to what Steve has in his screenshot. Are we expected to filter the depth images before using them?

**Comment by tangketan** [comment]
Yes, you are suggested to filter the depth images before use. We provide the **raw** depth image, and it is a usual practice to filter depth images before use (usually we use `filterSpecke`or median).

**Comment by andre-nguyen** [comment]
Thanks for the tip, it definitely helps. My images are still quite noisier than what I see in the paper. Could you suggest settings for filterSpeckle?

**Comment by tangketan** [comment]
@andre-nguyen It really depends on your application. I can only provide a reasonable range: newVal=-16, maxSpeckleSize in [50,500], maxDiff = [1,3]*multiplier (16 for 4-bit fraction disparity).

**Comment by andre-nguyen** [comment]
Thanks!  Also, if you don't mind, what is your opinion on the bilateral filter compared to filterspeckle?

**Comment by tangketan** [comment]
@andre-nguyen  Bilateral filter will blur the depth image, while filterSpeckle only affects speckles. If we need to present the depth image to a human, bilateral filter is good, otherwise I prefer speckle filter.
